version: '2.2'

services:
  database:
    image: postgres:10
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
    - '5432:5432'
    volumes:
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
