version: '2.2'

services:
  database:
    image: postgres:10
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
    - '5432:5432'
    volumes:
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

#  application:
#    build:
#      context: .
#    environment:
#      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/test"
#    ports:
#    - 8080:8080
#    depends_on:
#      - database